server:
  port: ${spos.server.port}
spring:
  application:
    name: service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${spos.db.host}:3306/${spos.db.database}?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${spos.db.username}
    password: ${spos.db.password}
  redis:
    database: 0
    host: 10.160.4.147
    port: 6379
    password: 123456
  data:
    mongodb:
      host: 10.160.4.147
      port: 27017
      database: spos
#      uri: mongodb://10.160.4.147:27017/spos
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    cn.bupt.dssc: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 南太意见接口文档
    description: "南太意见接口文档"
    email: Yiming_Lee2001@bupt.edu.cn
    concat: 南太意见开发组
    url: https://www.bupt.edu.cn
    version: v2.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - cn.bupt.dssc.controller
spos:
  jwt:
    location: classpath:spos.jks
    alias: spos
    password: agoodoffer
    tokenTTL: 30m
  auth:
    excludePaths:
      - /entity/**
      - /chat/**
      - /article/**
      - /users/**
      - /hi